baseUrl: https://crucialfelix.github.io
languageCode: en-us
theme: github.com/panr/hugo-theme-terminal
paginate: 5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: orange
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 3
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width
  fullWidthTheme: false
  # center theme with default width
  centerTheme: true
  twitter:
    creator: crucialfelix

module:
  imports:
  - path: github.com/panr/hugo-theme-terminal

languages:
  en:
    languageName: English
    title: Chris Sattinger
    subtitle: Technical
    keywords: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: chris.sattinger
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: Posts
        url: /
      # - identifier: showcase
      #   name: Showcase
      #   url: /showcase